language: node_js

addons:
  ssh_known_hosts: "${SERVER_HOST}"

install: true

script: true

before_deploy:
- openssl aes-256-cbc -K $encrypted_154e2cf5c0ed_key -iv $encrypted_154e2cf5c0ed_iv
  -in protected/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash ssh travis@${SERVER_HOST} scripts/deploy.sh
  on:
    branch: master
